name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff (linter)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff==0.15.4

      - name: Run Ruff
        run: ruff check scripts/

  mypy:
    name: Mypy (type checker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install mypy==1.19.1

      - name: Run Mypy
        run: mypy scripts/ --ignore-missing-imports
